name: Build and test docker images

on:
  pull_request:
    branches: [ 'main' ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

    - name: Checkout IUI
      uses: actions/checkout@v2

    - name: Build the stack
      run: ./build.sh

    - name: Test stack
      run: docker images
