name: Build and upload docker images

on:
  push:
    branches: [ 'main' ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

    - name: Checkout IUI
      uses: actions/checkout@v2

    - name: Build the stack
      run: docker-compose
              -f ./docker-compose.yml
              -f ./plugins/ros.docker-compose.yml
              -f ./plugins/isaac.docker-compose.yml build
              --build-arg REMOTE="ghcr.io/nasa"


    # - name: Log in to registry
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    # - name: Push Docker image
    #   run: |
    #     if [ "${{ github.repository_owner }}" = "nasa" ]; then docker push ghcr.io/${{ github.repository_owner }}/isaac:latest-astrobee-ubuntu16.04; fi;
    #     if [ "${{ github.repository_owner }}" = "nasa" ]; then docker push ghcr.io/${{ github.repository_owner }}/isaac:latest-ubuntu16.04; fi;
    #     if [ "${{ github.repository_owner }}" = "nasa" ]; then docker push ghcr.io/${{ github.repository_owner }}/isaac:astrobee-msgs-ubuntu16.04; fi;
    #     if [ "${{ github.repository_owner }}" = "nasa" ]; then docker push ghcr.io/${{ github.repository_owner }}/isaac:msgs-ubuntu16.04; fi;
